'use strict';

exports.BattlePokedex = {
	
	venusaur: {
		inherit: true,
		baseStats: {hp:80, atk:62, def:93, spa: 110, spd: 110, spe:80},
		abilities: {0: "Overgrow", H: "Thick Fat"},
	},
	charizard: {
		inherit: true,
		types: ["Fire", "Dragon", "caw"],
		baseStats: {hp: 78, atk: 74, def:80, spa:114, spd: 88, spe:110},
		abilities: {0: "Blaze", H: "Drought"},
	},
	blastoise: {
		inherit: true,
		baseStats: {hp: 79, atk: 60, def: 105, spa:108, spd: 110, spe:78},
		abilities: {0: "Torrent", H:"Mega Launcher"},
	},
	venomoth :{
		inherit: true,
		types: ["Bug", "Poison", "caw"],
		baseStats: {hp: 80, atk: 75, def: 70, spa: 100, spd: 85, spe: 100},
	},
	poliwrath: {
		inherit: true,
		baseStats: {hp: 90, atk: 105, def: 95, spa: 105, spd: 90, spe: 80},
	},
	hypno: {
		num: 97,
		species: "Hypno",
		types: ["Psychic"],
		baseStats: {hp: 85, atk: 73, def: 70, spa: 73, spd: 115, spe: 67},
		abilities: {0: "Insomnia", 1: "Pure Power", H: "Inner Focus"},
		heightm: 1.6,
		weightkg: 75.6,
		color: "Yellow",
		prevo: "drowzee",
		evoLevel: 26,
		eggGroups: ["Human-Like"],
	},
	gengar: {
		inherit: true,
		types: ["Ghost", "Poison", "caw"],
	},
	mrmime: {
		num: 122,
		species: "Mr. Mime",
		types: ["Psychic", "Fairy"],
		baseStats: {hp: 80, atk: 45, def: 65, spa: 110, spd: 120, spe: 100},
		abilities: {0: "Soundproof", 1: "Filter", H: "Technician"},
		heightm: 1.3,
		weightkg: 54.5,
		color: "Pink",
		prevo: "mimejr",
		evoLevel: 1,
		evoMove: "Mimic",
		eggGroups: ["Human-Like"],
	},
	lapras: {
		inherit: true,
		baseStats: {hp: 140, atk: 85, def: 100, spa: 90, spd: 100, spe: 60},
	},
	articuno: {
		inherit: true,
		baseStats: {hp: 100, atk: 115, def: 100, spa: 60, spd: 125, spe: 100}, 
		abilities: {0: "Pressure", H: "Snow Warning"},
	},
	zapdos: {
		inherit: true,
		baseStats: {hp: 100, atk: 75, def: 90, spa: 135, spd: 90, spe: 110},
		abilities: {0: "Pressure", H: "Drizzle"},
	},
	moltres: {
		inherit: true,
		baseStats: {hp: 90, atk: 80, def: 90, spa: 125, spd: 85, spe:130},
		abilities: {0: "Pressure", H: "Drought"},
	},
	meganium: {
		num: 154,
		species: "Meganium",
		types: ["Grass", "Fairy"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 80, atk: 93, def: 110, spa: 62, spd: 110, spe: 80},
		abilities: {0: "Overgrow", H: "Simple"},
		heightm: 1.8,
		weightkg: 100.5,
		color: "Green",
		prevo: "bayleef",
		evoLevel: 32,
		eggGroups: ["Monster", "Grass"],
	},
	typhlosion: {
		num: 157,
		species: "Typhlosion",
		types: ["Fire"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 78, atk: 74, def: 80, spa: 114, spd: 85, spe: 100},
		abilities: {0: "Blaze", H: "Flash Fire"},
		heightm: 1.7,
		weightkg: 79.5,
		color: "Yellow",
		prevo: "quilava",
		evoLevel: 36,
		eggGroups: ["Field"],
	},
	feraligatr: {
		num: 160,
		species: "Feraligatr",
		types: ["Water"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 105, atk: 108, def: 110, spa: 60, spd: 79, spe: 78},
		abilities: {0: "Torrent", H: "Sheer Force"},
		heightm: 2.3,
		weightkg: 88.8,
		color: "Blue",
		prevo: "croconaw",
		evoLevel: 30,
		eggGroups: ["Monster", "Water 1"],
	},
	delibird: {
		num: 225,
		species: "Delibird",
		types: ["Ice", "Flying"],
		baseStats: {hp: 85, atk: 105, def: 65, spa: 115, spd: 65, spe: 115},
		abilities: {0: "Vital Spirit", 1: "Snow Warning", H: "Insomnia"},
		heightm: 0.9,
		weightkg: 16,
		color: "Red",
		eggGroups: ["Water 1", "Field"],
	},
	sceptile: {
		num: 254,
		species: "Sceptile",
		types: ["Grass", "Dragon"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 70, atk: 85, def: 65, spa: 105, spd: 85, spe: 120},
		abilities: {0: "Overgrow", H: "Competitive"},
		heightm: 1.7,
		weightkg: 52.2,
		color: "Green",
		prevo: "grovyle",
		evoLevel: 36,
		eggGroups: ["Monster", "Dragon"],
		otherFormes: ["sceptilemega"],
	},
	swampert: {
		num: 260,
		species: "Swampert",
		types: ["Water", "Ground"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 100, atk: 110, def: 90, spa: 85, spd: 90, spe: 60},
		abilities: {0: "Torrent", H: "Water Bubble"},
		heightm: 1.5,
		weightkg: 81.9,
		color: "Blue",
		prevo: "marshtomp",
		evoLevel: 36,
		eggGroups: ["Monster", "Water 1"],
		otherFormes: ["swampertmega"],
	},
	meditite: {
		num: 307,
		species: "Meditite",
		types: ["Fighting", "Psychic"],
		baseStats: {hp: 30, atk: 40, def: 55, spa: 40, spd: 55, spe: 60},
		abilities: {0: "Huge Power", H: "Telepathy"},
		heightm: 0.6,
		weightkg: 11.2,
		color: "Blue",
		evos: ["medicham"],
		eggGroups: ["Human-Like"],
	},
	medicham: {
		num: 308,
		species: "Medicham",
		types: ["Fighting", "Psychic"],
		baseStats: {hp: 60, atk: 60, def: 75, spa: 60, spd: 75, spe: 80},
		abilities: {0: "Huge Power", H: "Telepathy"},
		heightm: 1.3,
		weightkg: 31.5,
		color: "Red",
		prevo: "meditite",
		evoLevel: 37,
		eggGroups: ["Human-Like"],
		otherFormes: ["medichammega"],
	},
	medichammega: {
		num: 308,
		species: "Medicham-Mega",
		baseSpecies: "Medicham",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fighting", "Psychic"],
		baseStats: {hp: 60, atk: 100, def: 85, spa: 80, spd: 85, spe: 100},
		abilities: {0: "Huge Power"},
		heightm: 1.3,
		weightkg: 31.5,
		color: "Red",
		eggGroups: ["Human-Like"],
		spritenum: 1000,
	},
	seviper: {
		inherit: true,
		types: ["Poison", "Dragon"],
		baseStats: {hp: 83, atk: 100, def: 70, spa: 100, spd: 70, spe: 95}
	},
	torterra: {
		num: 389,
		species: "Torterra",
		types: ["Grass", "Ground"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 95, atk: 119, def: 115, spa: 45, spd: 105, spe: 56},
		abilities: {0: "Overgrow", H: "Shell Armor"},
		heightm: 2.2,
		weightkg: 310,
		color: "Green",
		prevo: "grotle",
		evoLevel: 32,
		eggGroups: ["Monster", "Grass"],
	},
	empoleon: {
		num: 395,
		species: "Empoleon",
		types: ["Water", "Steel"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 94, atk: 46, def: 98, spa: 121, spd: 111, spe: 60},
		abilities: {0: "Torrent", H: "Competitive"},
		heightm: 1.7,
		weightkg: 84.5,
		color: "Blue",
		prevo: "prinplup",
		evoLevel: 36,
		eggGroups: ["Water 1", "Field"],
	},
	kricketune: {
		num: 402,
		species: "Kricketune",
		types: ["Bug"],
		baseStats: {hp: 87, atk: 105, def: 81, spa: 55, spd: 81, spe: 65},
		abilities: {0: "Swarm", H: "Technician"},
		heightm: 1,
		weightkg: 25.5,
		color: "Red",
		prevo: "kricketot",
		evoLevel: 10,
		eggGroups: ["Bug"],
	},
	serperior: {
		num: 497,
		species: "Serperior",
		types: ["Grass"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 75, def: 95, spa: 75, spd: 95, spe: 113},
		abilities: {0: "Overgrow", H: "Contrary"},
		heightm: 3.3,
		weightkg: 63,
		color: "Green",
		prevo: "servine",
		evoLevel: 36,
		eggGroups: ["Field", "Grass"],
	},
	emboar: {
		num: 500,
		species: "Emboar",
		types: ["Fire", "Fighting"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 110, atk: 123, def: 65, spa: 100, spd: 65, spe: 65},
		abilities: {0: "Blaze", H: "Contrary"},
		heightm: 1.6,
		weightkg: 150,
		color: "Red",
		prevo: "pignite",
		evoLevel: 36,
		eggGroups: ["Field"],
	},
	samurott: {
		num: 503,
		species: "Samurott",
		types: ["Water", "Fighting"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 95, atk: 100, def: 85, spa: 108, spd: 70, spe: 70},
		abilities: {0: "Torrent", H: "Contrary"},
		heightm: 1.5,
		weightkg: 94.6,
		color: "Blue",
		prevo: "dewott",
		evoLevel: 36,
		eggGroups: ["Field"],
	},
	simisage: {
		num: 512,
		species: "Simisage",
		types: ["Grass"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 108, def: 63, spa: 108, spd: 63, spe: 111},
		abilities: {0: "Gluttony", H: "Overgrow"},
		heightm: 1.1,
		weightkg: 30.5,
		color: "Green",
		prevo: "pansage",
		evoLevel: 1,
		eggGroups: ["Field"],
	},
	simisear: {
		num: 514,
		species: "Simisear",
		types: ["Fire"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 108, def: 63, spa: 108, spd: 63, spe: 111},
		abilities: {0: "Gluttony", H: "Blaze"},
		heightm: 1,
		weightkg: 28,
		color: "Red",
		prevo: "pansear",
		evoLevel: 1,
		eggGroups: ["Field"],
	},
	simipour: {
		num: 516,
		species: "Simipour",
		types: ["Water"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 108, def: 63, spa: 108, spd: 63, spe: 111},
		abilities: {0: "Gluttony", H: "Torrent"},
		heightm: 1,
		weightkg: 29,
		color: "Blue",
		prevo: "panpour",
		evoLevel: 1,
		eggGroups: ["Field"],
	},
	chesnaught: {
		inherit: true,
		baseStats: {hp: 98, atk: 107, def: 122, spa: 64, spd: 80, spe: 64},
		abilities: {0: "Overgrow", H: "Rough Skin"},
	},
	delphox: {
		inherit: true,
		baseStats: {hp: 75, atk: 114, def: 78, spa: 69, spd: 100, spe: 104},
		abilities: {0: "Blaze", H: "Pure Power"},
	},	
	ribombee: {
		inherit: true,
		types: ["Bug", "Fairy", "caw"],
		baseStats: {hp: 60, atk: 45, def: 50, spa: 115, spd: 60, spe: 124},
		abilities: {0: "Magic Guard", 1: "Shield Dust", H: "Sweet Veil"},
	},
	decideueye: {
		inherit: true,
		types: ["Grass", "Ghost", "caw"],
		baseStats: {hp: 78, atk: 127, def: 85, spa: 70, spd: 100, spe: 75},
	},
	incineroar: {
		inherit: true,
		baseStats: {hp: 95, atk: 125, def: 100, spa: 10, spd: 100, spe: 100},
	},
	pyukumuku: {
		num: 771,
		species: "Pyukumuku",
		types: ["Water"],
		baseStats: {hp: 155, atk: 5, def: 180, spa: 5, spd: 180, spe: 5},
		abilities: {0: "Innards Out", 1:"Poison Heal", H: "Unaware"},
		heightm: 0.3,
		weightkg: 1.2,
		color: "Black",
		eggGroups: ["Water 1"],
	},
	drampa: {
		num: 780,
		species: "Drampa",
		types: ["Normal", "Dragon"],
		baseStats: {hp: 83, atk: 45, def: 93, spa: 147, spd: 111, spe: 23},
		abilities: {0: "Berserk", 1: "Sap Sipper", H: "Simple"},
		heightm: 3,
		weightkg: 185,
		color: "White",
		eggGroups: ["Monster", "Dragon"],
	},
};
